In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [6]:
url = "file:///c:/Users/ahmed/OneDrive/Desktop/crash_data.csv"
df = pd.read_csv(url)

In [13]:
CrashesDF = df[df['Record Type'] == 1]
VehicleDF = df[df['Record Type'] == 2]
ParticipantsDF = df[df['Record Type'] == 3]

In [9]:
print(CrashesDF)

      Crash ID  Record Type  Vehicle ID  Participant ID  \
0      1809119            1         NaN             NaN
5      1809229            1         NaN             NaN
9      1809637            1         NaN             NaN
12     1810874            1         NaN             NaN
16     1812266            1         NaN             NaN
...        ...          ...         ...             ...
2716   1860371            1         NaN             NaN
2719   1860417            1         NaN             NaN
2724   1860427            1         NaN             NaN
2729   1860453            1         NaN             NaN
2734   1860771            1         NaN             NaN

      Participant Display Seq#  Vehicle Coded Seq#  Participant Vehicle Seq#  \
0                          NaN                 NaN                       NaN
5                          NaN                 NaN                       NaN
9                          NaN                 NaN                       NaN
12                         NaN                 NaN                       NaN
16                         NaN                 NaN                       NaN
...                        ...                 ...                       ...
2716                       NaN                 NaN                       NaN
2719                       NaN                 NaN                       NaN
2724                       NaN                 NaN                       NaN
2729                       NaN                 NaN                       NaN
2734                       NaN                 NaN                       NaN

      Serial #  Crash Month  Crash Day  ...  Participant Cause 2 Code  \
0      99992.0          3.0       14.0  ...                       NaN
5       2405.0          3.0        3.0  ...                       NaN
9       1811.0          5.0       17.0  ...                       NaN
12     99981.0          4.0        7.0  ...                       NaN
16      5970.0          7.0        8.0  ...                       NaN
...        ...          ...        ...  ...                       ...
2716    3344.0          4.0       19.0  ...                       NaN
2719    3385.0          4.0       20.0  ...                       NaN
2724    3396.0          4.0       13.0  ...                       NaN
2729    3423.0          4.0       22.0  ...                       NaN
2734    1465.0          5.0        6.0  ...                       NaN

      Participant Cause 3 Code  Participant Event 1 Code  \
0                          NaN                       NaN
5                          NaN                       NaN
9                          NaN                       NaN
12                         NaN                       NaN
16                         NaN                       NaN
...                        ...                       ...
2716                       NaN                       NaN
2719                       NaN                       NaN
2724                       NaN                       NaN
2729                       NaN                       NaN
2734                       NaN                       NaN

      Participant Event 2 Code  Participant Event 3 Code  \
0                          NaN                       NaN
5                          NaN                       NaN
9                          NaN                       NaN
12                         NaN                       NaN
16                         NaN                       NaN
...                        ...                       ...
2716                       NaN                       NaN
2719                       NaN                       NaN
2724                       NaN                       NaN
2729                       NaN                       NaN
2734                       NaN                       NaN

      BAC Test Results Code  Alcohol Use Reported  Drug Use Reported  \
0                       NaN                   NaN                NaN
5                       NaN                   NaN                NaN
9                       NaN                   NaN                NaN
12                      NaN                   NaN                NaN
16                      NaN                   NaN                NaN
...                     ...                   ...                ...
2716                    NaN                   NaN                NaN
2719                    NaN                   NaN                NaN
2724                    NaN                   NaN                NaN
2729                    NaN                   NaN                NaN
2734                    NaN                   NaN                NaN

      Participant Marijuana Use Reported  Participant Striker Flag
0                                    NaN                       NaN
5                                    NaN                       NaN
9                                    NaN                       NaN
12                                   NaN                       NaN
16                                   NaN                       NaN
...                                  ...                       ...
2716                                 NaN                       NaN
2719                                 NaN                       NaN
2724                                 NaN                       NaN
2729                                 NaN                       NaN
2734                                 NaN                       NaN

[508 rows x 157 columns]

In [20]:
CrashesDF = CrashesDF.reset_index()

In [25]:
VehicleDF = VehicleDF.reset_index()

In [30]:
ParticipantsDF = ParticipantsDF.reset_index()

ValueError: cannot insert level_0, already exists

In [28]:
CrashesDF = CrashesDF.dropna(axis=1,how='all')

In [26]:
VehicleDF = VehicleDF.dropna(axis=1,how='all')

In [27]:
VehicleDF

,index,Crash ID,Record Type,Vehicle ID,Vehicle Coded Seq#,Total Count of Persons Involved,Total Persons Using Safety Equipment,Total Persons Not Using Safety Equipment,Total Persons Safety Equipment Use Unknown,Vehicle Ownership Code,...,Vehicle Action Code,Vehicle Cause 1 Code,Vehicle Cause 2 Code,Vehicle Cause 3 Code,Vehicle Event 1 Code,Vehicle Event 2 Code,Vehicle Event 3 Code,Vehicle Exceeded Posted Speed Flag,Vehicle Hit & Run Flag,Safety Equipment Used Quantity
0,1,1809119,2,3409578.0,1.0,1.0,0.0,9.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1,3,1809119,2,3409579.0,2.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,2.0,0.0
2,6,1809229,2,3409765.0,1.0,1.0,0.0,4.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,10,1809637,2,3410470.0,1.0,1.0,0.0,1.0,0.0,0.0,...,62.0,10.0,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
4,13,1810874,2,3412622.0,1.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010,2727,1860427,2,3503379.0,2.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,3.0,0.0,0.0,3.0,0.0
1011,2730,1860453,2,3503423.0,1.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1012,2732,1860453,2,3503424.0,2.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1013,2735,1860771,2,3503992.0,1.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1014,2737,1860771,2,3503993.0,2.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [34]:
ParticipantsDF = ParticipantsDF.dropna(axis=1,how='all')

In [39]:
ParticipantsDF = df[df['Record Type'] == 3]

In [40]:
ParticipantsDF

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
2,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,9.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN
7,1809229,3,3409765.0,3888073.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
8,1809229,3,0.0,3888074.0,2.0,NaN,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
11,1809637,3,3410470.0,3888766.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,1860427,3,3503379.0,3990896.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2731,1860453,3,3503423.0,3990937.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2733,1860453,3,3503424.0,3990938.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2736,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2738,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [42]:
ParticipantsDF = ParticipantsDF.dropna(axis=1, how='all')

In [43]:
ParticipantsDF

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Safety Equipment Un-used Quantity,Safety Equipment Use Unknown Quantity,Vehicle Occupant Count,...,Non-Motorist Travel Direction To,Non-Motorist Location,Participant Action,Participant Error 1 Code,Participant Error 2 Code,Participant Error 3 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code
2,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
4,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,9.0,9.0,0.0
7,1809229,3,3409765.0,3888073.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
8,1809229,3,0.0,3888074.0,2.0,NaN,1.0,3.0,0.0,0.0,...,NaN,NaN,18.0,NaN,NaN,NaN,0.0,9.0,1.0,0.0
11,1809637,3,3410470.0,3888766.0,1.0,1.0,1.0,1.0,0.0,0.0,...,81.0,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,1860427,3,3503379.0,3990896.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2731,1860453,3,3503423.0,3990937.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2733,1860453,3,3503424.0,3990938.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2736,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2738,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [46]:
ParticipantsDF = ParticipantsDF.reset_index(drop=True)

In [48]:
ParticipantsDF = ParticipantsDF.drop('index',axis=1)

In [50]:
VehicleDF

,index,Crash ID,Record Type,Vehicle ID,Vehicle Coded Seq#,Total Count of Persons Involved,Total Persons Using Safety Equipment,Total Persons Not Using Safety Equipment,Total Persons Safety Equipment Use Unknown,Vehicle Ownership Code,...,Vehicle Action Code,Vehicle Cause 1 Code,Vehicle Cause 2 Code,Vehicle Cause 3 Code,Vehicle Event 1 Code,Vehicle Event 2 Code,Vehicle Event 3 Code,Vehicle Exceeded Posted Speed Flag,Vehicle Hit & Run Flag,Safety Equipment Used Quantity
0,1,1809119,2,3409578.0,1.0,1.0,0.0,9.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1,3,1809119,2,3409579.0,2.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,2.0,0.0
2,6,1809229,2,3409765.0,1.0,1.0,0.0,4.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,10,1809637,2,3410470.0,1.0,1.0,0.0,1.0,0.0,0.0,...,62.0,10.0,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
4,13,1810874,2,3412622.0,1.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010,2727,1860427,2,3503379.0,2.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,3.0,0.0,0.0,3.0,0.0
1011,2730,1860453,2,3503423.0,1.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1012,2732,1860453,2,3503424.0,2.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1013,2735,1860771,2,3503992.0,1.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1014,2737,1860771,2,3503993.0,2.0,0.0,0.0,1.0,0.0,9.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [49]:
ParticipantsDF

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Safety Equipment Un-used Quantity,Safety Equipment Use Unknown Quantity,Vehicle Occupant Count,...,Non-Motorist Travel Direction To,Non-Motorist Location,Participant Action,Participant Error 1 Code,Participant Error 2 Code,Participant Error 3 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code
0,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
1,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,9.0,9.0,0.0
2,1809229,3,3409765.0,3888073.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,1809229,3,0.0,3888074.0,2.0,NaN,1.0,3.0,0.0,0.0,...,NaN,NaN,18.0,NaN,NaN,NaN,0.0,9.0,1.0,0.0
4,1809637,3,3410470.0,3888766.0,1.0,1.0,1.0,1.0,0.0,0.0,...,81.0,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,1860427,3,3503379.0,3990896.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1212,1860453,3,3503423.0,3990937.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1213,1860453,3,3503424.0,3990938.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1214,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1215,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [53]:
CrashesDF = CrashesDF.drop('index',axis=1)

In [54]:
CrashesDF

,Crash ID,Record Type,Serial #,Crash Month,Crash Day,Crash Year,Week Day Code,Crash Hour,County Code,City Section ID,...,Total Pedestrian Count,Total Pedestrian Fatality Count,Total Pedestrian Non-Fatal Injury Count,Total Pedalcyclist Count,Total Pedalcyclist Fatality Count,Total Pedalcyclist Non-Fatal Injury Count,Total Unknown Non-Motorist Count,Total Unknown Non-Motorist Fatality Count,Total Unknown Non-Motorist Injury Count,Total Vehicle Occupant Count
0,1809119,1,99992.0,3.0,14.0,2019.0,5.0,14.0,26.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,3.0,2.0,0.0,1.0
1,1809229,1,2405.0,3.0,3.0,2019.0,1.0,2.0,3.0,185.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0
2,1809637,1,1811.0,5.0,17.0,2019.0,6.0,99.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
3,1810874,1,99981.0,4.0,7.0,2019.0,1.0,0.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0
4,1812266,1,5970.0,7.0,8.0,2019.0,2.0,14.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,5.0,5.0,2.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,1860371,1,3344.0,4.0,19.0,2019.0,6.0,20.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
504,1860417,1,3385.0,4.0,20.0,2019.0,7.0,15.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,0.0,0.0
505,1860427,1,3396.0,4.0,13.0,2019.0,7.0,21.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,4.0,4.0,3.0,0.0,1.0
506,1860453,1,3423.0,4.0,22.0,2019.0,2.0,12.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,0.0,0.0
507,1860771,1,1465.0,5.0,6.0,2019.0,2.0,15.0,3.0,185.0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,1.0

In [55]:
VehicleDF

,Crash ID,Record Type,Vehicle ID,Vehicle Coded Seq#,Total Count of Persons Involved,Total Persons Using Safety Equipment,Total Persons Not Using Safety Equipment,Total Persons Safety Equipment Use Unknown,Vehicle Ownership Code,Vehicle Special Use Code,...,Vehicle Action Code,Vehicle Cause 1 Code,Vehicle Cause 2 Code,Vehicle Cause 3 Code,Vehicle Event 1 Code,Vehicle Event 2 Code,Vehicle Event 3 Code,Vehicle Exceeded Posted Speed Flag,Vehicle Hit & Run Flag,Safety Equipment Used Quantity
0,1809119,2,3409578.0,1.0,1.0,0.0,9.0,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1,1809119,2,3409579.0,2.0,1.0,0.0,1.0,0.0,0.0,3.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,2.0,0.0
2,1809229,2,3409765.0,1.0,1.0,0.0,4.0,0.0,1.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,1809637,2,3410470.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,62.0,10.0,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
4,1810874,2,3412622.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010,1860427,2,3503379.0,2.0,0.0,0.0,1.0,0.0,9.0,6.0,...,NaN,NaN,NaN,0.0,0.0,3.0,0.0,0.0,3.0,0.0
1011,1860453,2,3503423.0,1.0,0.0,0.0,1.0,0.0,9.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1012,1860453,2,3503424.0,2.0,0.0,0.0,1.0,0.0,9.0,6.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1013,1860771,2,3503992.0,1.0,0.0,0.0,1.0,0.0,9.0,3.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1014,1860771,2,3503993.0,2.0,0.0,0.0,1.0,0.0,9.0,1.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [57]:
ParticipantsDF = ParticipantsDF.dropna(axis=1, how='all')

In [58]:
ParticipantsDF

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Safety Equipment Un-used Quantity,Safety Equipment Use Unknown Quantity,Vehicle Occupant Count,...,Non-Motorist Travel Direction To,Non-Motorist Location,Participant Action,Participant Error 1 Code,Participant Error 2 Code,Participant Error 3 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code
0,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
1,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,9.0,9.0,0.0
2,1809229,3,3409765.0,3888073.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,1809229,3,0.0,3888074.0,2.0,NaN,1.0,3.0,0.0,0.0,...,NaN,NaN,18.0,NaN,NaN,NaN,0.0,9.0,1.0,0.0
4,1809637,3,3410470.0,3888766.0,1.0,1.0,1.0,1.0,0.0,0.0,...,81.0,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,1860427,3,3503379.0,3990896.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1212,1860453,3,3503423.0,3990937.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1213,1860453,3,3503424.0,3990938.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1214,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1215,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [64]:
#assertion: Every crash record has a valid id
for index in range(len(CrashesDF)):
    if(CrashesDF['Crash ID'].iloc[index] > 1):
        print(CrashesDF['Crash ID'].iloc[index])

1809119
1809229
1809637
1810874
1812266
1815964
1816804
1826266
1826321
1826490
1826513
1826673
1826794
1826971
1827119
1827863
1827872
1827907
1828231
1828287
1828314
1828373
1828552
1828709
1828977
1828982
1829693
1829718
1829755
1829763
1829797
1829853
1829867
1829871
1829928
1829983
1829988
1830030
1830038
1830046
1830165
1830217
1830243
1831161
1831660
1831698
1832302
1832348
1833315
1833381
1833535
1833678
1833867
1833899
1833971
1833979
1833986
1834003
1834029
1834096
1834202
1834407
1834440
1834574
1834655
1834846
1834858
1835060
1835061
1835182
1835197
1835205
1835211
1835217
1835225
1835231
1835315
1835316
1835322
1835330
1835332
1835374
1835382
1835386
1835459
1835471
1835511
1835592
1835606
1835807
1836755
1836788
1836814
1836948
1837049
1837085
1837128
1837131
1837205
1837283
1837334
1837497
1837551
1837808
1837834
1838047
1838362
1838375
1838403
1838434
1838471
1838549
1838681
1839606
1839856
1840093
1840135
1840155
1840221
1840265
1840295
1840424
1840563
1840583
1840588
1840610
1840614
1840664
1840680
1840832
1840874
1840905
1841009
1841013
1841019
1841052
1841151
1841157
1841212
1841331
1841336
1841343
1841361
1841369
1841376
1841436
1841498
1841506
1841641
1841685
1841691
1841693
1841708
1841725
1841766
1841806
1841855
1841914
1842069
1842180
1842244
1842388
1842703
1842741
1842822
1842862
1843136
1843196
1843399
1843400
1843445
1843562
1843658
1843709
1843746
1843752
1843763
1843796
1843814
1843842
1843872
1843940
1843953
1844151
1844301
1844339
1844458
1844484
1844488
1844762
1844813
1844857
1844942
1844976
1845024
1845085
1845101
1845113
1845254
1845255
1845302
1845326
1845378
1845474
1845603
1845619
1845672
1845727
1845755
1845835
1845949
1845964
1845971
1845975
1845982
1846015
1846016
1846021
1846139
1846145
1846158
1846237
1846303
1846318
1846364
1846373
1846424
1846442
1846452
1846543
1846555
1846575
1846641
1846699
1846707
1846797
1846812
1846840
1846965
1847023
1847026
1847080
1847084
1847184
1847234
1847302
1847308
1847313
1847332
1847352
1847358
1847366
1847371
1847378
1847385
1847483
1847491
1847500
1847540
1847575
1847667
1847722
1847889
1847898
1847900
1847935
1847949
1847958
1848047
1848054
1848083
1848156
1848222
1848270
1848337
1848347
1848359
1848489
1848512
1848553
1848565
1848616
1848719
1848792
1848895
1848913
1849019
1849023
1849220
1849271
1849286
1849289
1849323
1849337
1849386
1849472
1849480
1849501
1849503
1849552
1849597
1849637
1849683
1849777
1849815
1849893
1849940
1849971
1850002
1850038
1850223
1850230
1850352
1850368
1850651
1850653
1850737
1850744
1850772
1850791
1850810
1850874
1850879
1850898
1850911
1850939
1850968
1850983
1851014
1851035
1851041
1851062
1851072
1851075
1851097
1851131
1851142
1851178
1851189
1851193
1851272
1851274
1851313
1851365
1851526
1851540
1851552
1851557
1851558
1851564
1851581
1851609
1851688
1851693
1851700
1851706
1851721
1851723
1851759
1851776
1851837
1851849
1851940
1851959
1851966
1852005
1852048
1852070
1852116
1852143
1852165
1852201
1852212
1852223
1852287
1852367
1852369
1852380
1852381
1852384
1852385
1852404
1852464
1852483
1852562
1852623
1852657
1852691
1852735
1852769
1852773
1852807
1852828
1852853
1852870
1852889
1852933
1852934
1852937
1852965
1852981
1853011
1853019
1853209
1853242
1853265
1853304
1853339
1853353
1853448
1853466
1853499
1853505
1853514
1853517
1853519
1853543
1853582
1853585
1853606
1853699
1853728
1853731
1853788
1853809
1853845
1853856
1853862
1853863
1853879
1853892
1853898
1853962
1854007
1854013
1854063
1854066
1854071
1854092
1854099
1854169
1854273
1854286
1854309
1854335
1854338
1854339
1854347
1854392
1854398
1854483
1854569
1854731
1854794
1854861
1854881
1854887
1854987
1854997
1855110
1855361
1855400
1855571
1855657
1855808
1855937
1855957
1856211
1856237
1856784
1857340
1857364
1857401
1857514
1857668
1858032
1858057
1858160
1858180
1858328
1858585
1858607
1858723
1858727
1858806
1858869
1858965
1859192
1859233
1859239
1859379
1859422
1859523
1859565
1859613
1859616
1859785
1860007
1860036
1860043
1860053
1860257
1860289
1860371
1860417
1860427
1860453
1860771

In [65]:
#assertion: Every participant record has a valid participant id
for index in range(len(ParticipantsDF)):
    if(ParticipantsDF['Participant ID'].iloc[index] < 1):
        print(index)

In [67]:
#assertion: Every vehicle record has a valid vehicle id
for index in range(len(VehicleDF)):
    if(VehicleDF['Vehicle ID'].iloc[index] > 1):
        print(index)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014